// src/utils/flagReasons.js
//
// "Why Was This Building Flagged?" — explainability layer.
//
// IMPORTANT (per spec): these are RULE-BASED explanations derived from
// existing model outputs (confidence, regularization method, etc.), not a
// natural-language explanation generated by the AI itself. Keep the wording
// in the UI honest about that distinction.

// Thresholds — kept in one place so priority + reasons never disagree.
export const CONFIDENCE_THRESHOLDS = {
  HIGH_PRIORITY_BELOW: 0.60,   // below this -> HIGH priority candidate
  MEDIUM_PRIORITY_BELOW: 0.80, // below this -> MEDIUM priority candidate
};

/**
 * Recomputes a priority tier purely from confidence, for cases where the
 * caller wants a rule derived independently of the pre-baked
 * `review_priority` string on the record. Not required for rendering (we
 * trust the existing field), but kept for transparency / testability.
 */
export function computeConfidencePriority(building) {
  const p = building?.mean_pixel_probability ?? 1;
  if (p < CONFIDENCE_THRESHOLDS.HIGH_PRIORITY_BELOW) return 'HIGH';
  if (p < CONFIDENCE_THRESHOLDS.MEDIUM_PRIORITY_BELOW) return 'MEDIUM';
  return 'LOW';
}

/**
 * Returns a structured list of flag reasons for a building, e.g.:
 * [{ id, title, detail, severity }]
 *
 * severity: 'high' | 'medium' | 'info' — purely for badge coloring.
 */
export function getFlagReasons(building) {
  if (!building) return [];

  const reasons = [];
  const prob = building.mean_pixel_probability ?? null;
  const roofConf = building.roof_confidence ?? null;
  const isFlagged = !!building.review_priority && !building.review_priority.startsWith('LOW');

  // 1. Low segmentation confidence
  if (prob !== null && prob < CONFIDENCE_THRESHOLDS.MEDIUM_PRIORITY_BELOW) {
    reasons.push({
      id: 'low_confidence',
      title: 'Low Segmentation Confidence',
      detail: `Model confidence: ${(prob * 100).toFixed(0)}%`,
      severity: prob < CONFIDENCE_THRESHOLDS.HIGH_PRIORITY_BELOW ? 'high' : 'medium',
    });
  }

  // 2. Boundary uncertainty — inferred from the regularization method the
  // pipeline had to fall back to (edge-straightening implies the raw mask
  // boundary was too irregular to snap to a clean rectangle).
  if (building.regularization_method === 'edge_straightened') {
    reasons.push({
      id: 'boundary_uncertainty',
      title: 'Boundary Uncertainty',
      detail: 'The detected building boundary contains areas of ambiguity (edge-straightened rather than rectangle-snapped).',
      severity: 'medium',
    });
  }

  // 3. Roof classification uncertainty
  if (roofConf !== null && roofConf < 0.85) {
    reasons.push({
      id: 'roof_uncertainty',
      title: 'Roof Classification Uncertainty',
      detail: `The system cannot clearly distinguish between detected roof-material classes (roof confidence ${(roofConf * 100).toFixed(0)}%).`,
      severity: roofConf < 0.6 ? 'high' : 'medium',
    });
  }

  // 4. Change detection (only present on records enriched by change_detection.py)
  if (building.change_status && building.change_status !== 'unchanged') {
    reasons.push({
      id: 'change_detected',
      title: 'Change Detected Between Imagery Passes',
      detail: `Flagged as "${building.change_status}" relative to the prior imagery pass.`,
      severity: 'high',
    });
  }

  // 5. Imagery quality warning — small/ambiguous geometry combined with mid confidence
  //    is used as a stand-in signal for local contrast/quality issues, since a
  //    per-building imagery-quality score isn't produced upstream.
  if (prob !== null && prob < CONFIDENCE_THRESHOLDS.MEDIUM_PRIORITY_BELOW && building.area_m2 && building.area_m2 < 40) {
    reasons.push({
      id: 'imagery_quality',
      title: 'Imagery Quality Warning',
      detail: 'Local image contrast may affect segmentation accuracy for small structures.',
      severity: 'info',
    });
  }

  // 6. Unusual geometry — very small or very large relative to typical footprints
  if (building.area_m2 && (building.area_m2 < 20 || building.area_m2 > 400)) {
    reasons.push({
      id: 'unusual_geometry',
      title: 'Unusual Building Geometry',
      detail: `Footprint area (${building.area_m2} m²) falls outside the typical range for this village.`,
      severity: 'info',
    });
  }

  // Fallback: if the record is flagged (MEDIUM/HIGH) but none of the above
  // rules fired, still explain why — otherwise the section would render empty.
  if (isFlagged && reasons.length === 0) {
    reasons.push({
      id: 'general_review',
      title: 'Flagged for Spot-Check',
      detail: 'This detection fell into the model\'s review band and was queued for manual verification.',
      severity: 'medium',
    });
  }

  return reasons;
}

/**
 * A single recommended human action string, derived from the reasons list.
 */
export function getRecommendedAction(building) {
  const reasons = getFlagReasons(building);
  if (reasons.length === 0) return null;

  const ids = reasons.map(r => r.id);
  if (ids.includes('boundary_uncertainty')) {
    return 'Verify the building boundary before accepting the detection.';
  }
  if (ids.includes('roof_uncertainty')) {
    return 'Confirm the roof material visually before using this record for tax classification.';
  }
  if (ids.includes('change_detected')) {
    return 'Confirm the change against the latest imagery pass before updating records.';
  }
  if (ids.includes('low_confidence')) {
    return 'Manually verify this detection before auto-accepting.';
  }
  return 'Review this detection before accepting.';
}
